spring:
  application:
    name: AUTH-TEMPLATE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: Chipheo2k3@

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret-key: ++Q1Jr1p0nd90O1vtNCpbsfbQgryfuCTKlNakcI5Jy/CYNviF5ron1/sjZ6R+cU3/mI3HxJ8OA9h263EQpLp9/flcUq4fHGhF+n7mzIyQLk=
